### ISSUE TITLE
Covariates collinear with fixed effects not correctly dropped

### ISSUE THREAD

**Issue by Nosferican** [FixedEffects/FixedEffectModels.jl#14]
Using a standard unbalanced panel data set such as: 
```
qui webuse nlswork, clear
xtset idcode year
encode race, g(Race)
```
The correct output for a two-way fixed effects is given by:
```
reghdfe ln_wage hours i.Race, a(idcode year)
```
or
```
xtreg ln_wage hours i.Race i.year
```
The same estimated coefficients can be obtained through R's plm package
```
model = plm(ln_wage ~ hours + race, data, model = 'within', effect = 'twoways')
```
Currently the package computes the wrong estimates. I believe the issue lies in using a quasi-demeaning transformation for multi-way fixed effects. I have an implementation of the two-ways fixed effects in [Econometrics.jl](https://github.com/JuliaEconometrics/Econometrics.jl) which uses a slightly more efficient way of the original Wansbeek and Kapteyn ([1989](http://dx.doi.org/10.1016/0304-4076(89)90066-3)) estimator. However, I would love to have Correia [2016](http://scorreia.com/research/hdfe.pdf) for a more efficient multi-way fixed effects implementation.

As a feature request, could the implementation have an API:
```
fun(fe::AbstractMatrix, X::AbstractMatrix, y::AbstractVector)
```
so it may be used more flexibly for other packages as well? For example, for error component models of unobserved effects models an efficient way for one-way and two-way fixed effects (panel and temporal).

**Comment by matthieugomez** [comment]
The package supports multi-way fixed effects.
Could you post the code that returns wrong estimates? 
Something akin to the tests of the package [here](https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/test/reg.jl)

**Comment by Nosferican** [comment]
## Housekeeping
```
using DataFrames
using FixedEffectModels
using Base.Test
```

## Loading the data and clean it from the export text file from Stata.
```
df = readtable(joinpath(dirname(@__FILE__), "test_files/", "NLS.csv"))
for var in names(df)
    if eltype(df[var]) .== String
        pool!(df, var)
    elseif sort(setdiff(unique(df[var]), [NA])) == [0, 1]
        mapper = Dict{Int64, String}([(0, "False"), (1, "True")])
        df[var] = get.(mapper, df[var], NA)
        pool!(df, var)
    end
end
pool!(df, [:idcode, :year]) # Treating the temporal ID as categorical variables for the fixed effects
head(df)
```
## Estimate the two-ways fixed effects model
### First model with two continuous variables and one time-invariant (fe invariant) categorical variable. 
```
model1 = reg(df, @model(ln_wage ~ hours + race, fe = idcode + year))
```
The continuous variables are correctly estimated, but the fixed effect invariant variables are estimated when they should be dropped.
### Second model with two continuous variables, one categorical variable, and one time invariant (fe invariant) categorical variable.
```
model2 = reg(df, @model(ln_wage ~ hours + union + race, fe = idcode + year))
```
The reference category for the categorical variable is estimated with a zero coefficient and `NaN` for standard errors. The time-invariant categorical variable still has estimates.

## Tests
```
function tocompare(Julia::String, Stata::Float64)
    isapprox(parse(Julia), Stata,
        atol = 1 / 10^min(length(match(r"(?<integers>\d+).(?<digits>\d+)", string(Stata))["digits"]),
            (6 - parse(Julia[(end - 2):end]))))
end
@test all(tocompare.(map(elem -> @sprintf("%e", elem), coef(model1)[1:2]),
            [.0001506, .0209924]))
@test all(tocompare.(map(elem -> @sprintf("%e", elem), coef(model2)[1:3]),
            [-.0021106, 0.0177158, 0.1030754]))
```
I put the values from reghdfe. One of the most severe consequences of estimating non-identifiable variables as it currently does is that it yields incorrect vcov estimates for all coefficients. You can verify that with `vcov = cluster(idcode)` for example.

**Comment by matthieugomez** [comment]
It is just a matter of relaxing the tolerance when checking for collinearity. I corrected the code and added a test in https://github.com/matthieugomez/FixedEffectModels.jl/commit/a303f81c6817d2c8f7932b488117f4c8af4a4094

**Comment by Nosferican** [comment]
I just tried to verify the new output with `Pkg.checkout` and updating it from master, but still getting the same behavior as before. For making the full rank matrix I use this code and it handles all the tests I could think of:
```
function linear_independent(obj::AbstractMatrix)
	@assert reduce(-, size(obj)) > 0 "Design matrix has more features than observations."
	tmp = RowEchelon.rref(round.(obj, 12))
	mapslices(col -> col[max(1, findfirst(col))] .== 1., tmp, 1)[1,:]
end
function get_fullrank(obj::AbstractMatrix)
	LinearIndependent = linear_independent(obj)
	output = obj[:,LinearIndependent]
	output, LinearIndependent
end
```
`LinearIndependent` is just the `Vector{Bool}` I use to update `coefnames`. `rref` is from [RowEchelon.jl](https://github.com/blegat/RowEchelon.jl/). I tried a few methods (eigenvalues, rref, etc.) and through some experimentation found out row echelon as the most robust. In case the issue is still with checking collinearity and that method is helpful.

**Comment by matthieugomez** [comment]
Thanks. I have just pushed https://github.com/matthieugomez/FixedEffectModels.jl/commit/d44dbf73472eed3c859bbcde3ce803f7e413d16b and it should be good now.
I now use a different criteria for variables that were demeaned, similar to what [reghdfe does](https://github.com/sergiocorreia/reghdfe/blob/72d7869e84e3a0f6b6752e423f2a5d6e21d46132/src/reghdfe_class.mata#L484
).

**Comment by Nosferican** [comment]
Seems to be working properly now. :)
There was still and issue with the clustered standard errors, but I can open a different issue for it if you want.

**Comment by matthieugomez** [comment]
As for the API request, I simply recommend to use the [lsmr](https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/src/utils/lsmr.jl
) function, that allows to demean any variable with respect to a set of fixed effects.

**Comment by Nosferican** [comment]
Would you be able, for my benefit, to give me a quick how to use `FixedEffectModels.lsmr!` based on:
```
fm = @formula(y ~ x1 + x2)
fe = @formula(y ~ fe1 + fe2)
df = df[union(DataFrames.allvars(fm), DataFrames.allvars(fe))]
completecases!(df)
X = getfield(ModelMatrix(ModelFrame(fm, df)), :m)
D = getfield(ModelMatrix(ModelFrame(fe, df)), :m)
y = Vector(df[getfield(fm, :lhs)])
```
in order to obtain the transformed design matrix and response vector?

**Comment by Nosferican** [comment]
Given a response vector `y::AbstractVector`, model matrix `X::AbstractMatrix`, and matrix of indicators for fixed effects `D::AbstractMatrix`. Could you indulge me on how to use `lsmr` for the annihilator matrix? The documentation said that the first step was to have `y`, `X` regressed on `D`, but I am a lost at the steps. Thanks!

**Comment by matthieugomez** [comment]
@Nosferican To make it easier, I have put all the FixedEffect operations in a separate package https://github.com/matthieugomez/FixedEffects.jl
